version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: build(deps)
  groups:
    development-tools:
      dependency-type: development
      update-types:
      - minor
      - patch
