// 悬浮球音乐播放器
// 可拖动，默认左侧中下，点击展开迷你播放器

var style = '<style>'
+ '#music-ball{position:fixed;left:30px;bottom:35%;z-index:9999;cursor:grab;user-select:none;-webkit-user-select:none}'
+ '#music-ball:active{cursor:grabbing}'
+ '#music-ball .ball{width:52px;height:52px;border-radius:50%;background:linear-gradient(135deg,#b48ead,#f4a9c0);display:flex;align-items:center;justify-content:center;box-shadow:0 4px 20px rgba(180,142,173,0.5);transition:transform .3s,box-shadow .3s;animation:ballPulse 3s ease-in-out infinite}'
+ '#music-ball .ball:hover{transform:scale(1.12);box-shadow:0 6px 28px rgba(244,169,192,0.6)}'
+ '#music-ball .ball .icon{font-size:22px;color:#fff;pointer-events:none}'
+ '#music-ball .ball.playing{animation:ballSpin 4s linear infinite}'
+ '@keyframes ballPulse{0%,100%{box-shadow:0 4px 20px rgba(180,142,173,0.4)}50%{box-shadow:0 4px 28px rgba(244,169,192,0.6)}}'
+ '@keyframes ballSpin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}'
+ '#music-ball .ball.playing:hover{animation:none;transform:scale(1.12)}'

// 迷你播放器面板
+ '#music-panel{position:absolute;left:64px;top:50%;transform:translateY(-50%);width:280px;background:rgba(26,16,37,0.92);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid rgba(180,142,173,0.2);border-radius:16px;padding:16px;color:#f0e6f6;display:none;box-shadow:0 12px 40px rgba(0,0,0,0.4)}'
+ '#music-panel.show{display:block;animation:panelIn .3s cubic-bezier(0.34,1.56,0.64,1)}'
+ '@keyframes panelIn{0%{opacity:0;transform:translateY(-50%) scale(0.9) translateX(-10px)}100%{opacity:1;transform:translateY(-50%) scale(1) translateX(0)}}'
+ '#music-panel .song-info{margin-bottom:12px}'
+ '#music-panel .song-title{font-size:14px;font-weight:600;color:#d4b5e0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'
+ '#music-panel .song-artist{font-size:11px;color:#c8b8d4;margin-top:2px}'
+ '#music-panel .controls{display:flex;align-items:center;justify-content:center;gap:16px;margin:10px 0}'
+ '#music-panel .ctrl-btn{background:none;border:none;color:#f0e6f6;font-size:18px;cursor:pointer;padding:6px;border-radius:50%;transition:all .2s}'
+ '#music-panel .ctrl-btn:hover{background:rgba(180,142,173,0.2)}'
+ '#music-panel .ctrl-btn.main{font-size:24px;background:rgba(180,142,173,0.15);padding:8px}'
+ '#music-panel .progress-wrap{width:100%;height:4px;background:rgba(180,142,173,0.2);border-radius:2px;cursor:pointer;margin:8px 0}'
+ '#music-panel .progress-bar{height:100%;background:linear-gradient(90deg,#b48ead,#f4a9c0);border-radius:2px;width:0%;transition:width .3s}'
+ '#music-panel .time-row{display:flex;justify-content:space-between;font-size:10px;color:#c8b8d4}'
+ '#music-panel .playlist{max-height:160px;overflow-y:auto;margin-top:10px;border-top:1px solid rgba(180,142,173,0.15);padding-top:8px}'
+ '#music-panel .playlist::-webkit-scrollbar{width:4px}'
+ '#music-panel .playlist::-webkit-scrollbar-thumb{background:rgba(180,142,173,0.3);border-radius:2px}'
+ '#music-panel .pl-item{display:flex;align-items:center;padding:6px 8px;border-radius:8px;cursor:pointer;font-size:12px;transition:background .2s}'
+ '#music-panel .pl-item:hover{background:rgba(180,142,173,0.15)}'
+ '#music-panel .pl-item.active{background:rgba(244,169,192,0.15);color:#f4a9c0}'
+ '#music-panel .pl-item .pl-idx{width:20px;color:#c8b8d4;font-size:10px}'
+ '#music-panel .pl-item .pl-name{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'
+ '#music-panel .pl-item .pl-auth{font-size:10px;color:#8a7a94;margin-left:8px;white-space:nowrap}'
+ '@media(max-width:768px){#music-ball{display:none}}'
+ '</style>';

var html = '<div id="music-ball">'
+ '<div class="ball" id="music-ball-btn"><span class="icon">♪</span></div>'
+ '<div id="music-panel">'
+ '  <div class="song-info">'
+ '    <div class="song-title" id="mp-title">加载中...</div>'
+ '    <div class="song-artist" id="mp-artist"></div>'
+ '  </div>'
+ '  <div class="controls">'
+ '    <button class="ctrl-btn" id="mp-prev" title="上一首">⏮</button>'
+ '    <button class="ctrl-btn main" id="mp-play" title="播放/暂停">▶</button>'
+ '    <button class="ctrl-btn" id="mp-next" title="下一首">⏭</button>'
+ '  </div>'
+ '  <div class="progress-wrap" id="mp-progress-wrap"><div class="progress-bar" id="mp-progress"></div></div>'
+ '  <div class="time-row"><span id="mp-cur">0:00</span><span id="mp-dur">0:00</span></div>'
+ '  <div class="playlist" id="mp-playlist"></div>'
+ '</div>'
+ '</div>';

// 隐藏原生 APlayer
var hideAplayer = '<style>.aplayer{display:none!important}</style>';

hexo.extend.injector.register('head_end', style + hideAplayer);
hexo.extend.injector.register('body_end', '<script>'
+ '(function(){'
+ '  var API="https://api.injahow.cn/meting/?type=playlist&id=2690018998";'
+ '  var songs=[], curIdx=0, audio=new Audio(), playing=false, panelOpen=false;'
+
+ '  function init(){'
+ '    fetch(API).then(function(r){return r.json()}).then(function(d){'
+ '      songs=Array.isArray(d)?d:(d.data||[]);'
+ '      renderPlaylist();'
+ '      if(songs.length>0)loadSong(0);'
+ '    }).catch(function(){'
+ '      document.getElementById("mp-title").textContent="歌单加载失败";'
+ '    });'
+ '  }'
+
+ '  function loadSong(i){'
+ '    curIdx=i;var s=songs[i];'
+ '    document.getElementById("mp-title").textContent=s.name||s.title||"未知";'
+ '    document.getElementById("mp-artist").textContent=s.artist||s.author||"";'
+ '    audio.src=s.url||"";'
+ '    updatePlaylistActive();'
+ '  }'
+
+ '  function togglePlay(){'
+ '    if(!audio.src)return;'
+ '    if(playing){audio.pause();playing=false;}'
+ '    else{audio.play().catch(function(){});playing=true;}'
+ '    document.getElementById("mp-play").textContent=playing?"⏸":"▶";'
+ '    var ball=document.getElementById("music-ball-btn");'
+ '    if(playing)ball.classList.add("playing");else ball.classList.remove("playing");'
+ '  }'
+
+ '  function prev(){curIdx=(curIdx-1+songs.length)%songs.length;loadSong(curIdx);if(playing)audio.play().catch(function(){});}'
+ '  function next(){curIdx=(curIdx+1)%songs.length;loadSong(curIdx);if(playing)audio.play().catch(function(){});}'
+
+ '  function renderPlaylist(){'
+ '    var pl=document.getElementById("mp-playlist");var h="";'
+ '    songs.forEach(function(s,i){'
+ '      h+="<div class=\\"pl-item\\" data-i=\\""+i+"\\">"'
+ '        +"<span class=\\"pl-idx\\">"+(i+1)+"</span>"'
+ '        +"<span class=\\"pl-name\\">"+(s.name||s.title||"")+"</span>"'
+ '        +"<span class=\\"pl-auth\\">"+(s.artist||s.author||"")+"</span>"'
+ '        +"</div>";'
+ '    });'
+ '    pl.innerHTML=h;'
+ '    pl.querySelectorAll(".pl-item").forEach(function(el){'
+ '      el.onclick=function(){loadSong(parseInt(this.dataset.i));audio.play().catch(function(){});playing=true;document.getElementById("mp-play").textContent="⏸";document.getElementById("music-ball-btn").classList.add("playing");};'
+ '    });'
+ '  }'
+
+ '  function updatePlaylistActive(){'
+ '    document.querySelectorAll("#mp-playlist .pl-item").forEach(function(el,i){'
+ '      el.classList.toggle("active",i===curIdx);'
+ '    });'
+ '  }'
+
+ '  audio.ontimeupdate=function(){'
+ '    if(!audio.duration)return;'
+ '    var pct=audio.currentTime/audio.duration*100;'
+ '    document.getElementById("mp-progress").style.width=pct+"%";'
+ '    document.getElementById("mp-cur").textContent=formatTime(audio.currentTime);'
+ '    document.getElementById("mp-dur").textContent=formatTime(audio.duration);'
+ '  };'
+ '  audio.onended=function(){next();};'
+
+ '  function formatTime(s){var m=Math.floor(s/60);var sec=Math.floor(s%60);return m+":"+(sec<10?"0":"")+sec;}'
+
+ '  document.getElementById("mp-play").onclick=togglePlay;'
+ '  document.getElementById("mp-prev").onclick=prev;'
+ '  document.getElementById("mp-next").onclick=next;'
+
+ '  document.getElementById("mp-progress-wrap").onclick=function(e){'
+ '    if(!audio.duration)return;'
+ '    var rect=this.getBoundingClientRect();'
+ '    audio.currentTime=(e.clientX-rect.left)/rect.width*audio.duration;'
+ '  };'
+
+ '  // 悬浮球点击展开面板'
+ '  document.getElementById("music-ball-btn").onclick=function(e){'
+ '    if(dragging)return;'
+ '    panelOpen=!panelOpen;'
+ '    document.getElementById("music-panel").classList.toggle("show",panelOpen);'
+ '  };'
+
+ '  // 拖动'
+ '  var dragEl=document.getElementById("music-ball");'
+ '  var dragging=false,startX,startY,origLeft,origBottom;'
+
+ '  // 从 localStorage 恢复位置'
+ '  var saved=localStorage.getItem("music-ball-pos");'
+ '  if(saved){'
+ '    try{var p=JSON.parse(saved);dragEl.style.left=p.left+"px";dragEl.style.bottom=p.bottom+"px";dragEl.style.top="auto";}catch(e){}'
+ '  }'
+
+ '  dragEl.onmousedown=function(e){'
+ '    dragging=false;startX=e.clientX;startY=e.clientY;'
+ '    var rect=dragEl.getBoundingClientRect();'
+ '    origLeft=rect.left;origBottom=window.innerHeight-rect.bottom;'
+ '    document.onmousemove=function(ev){'
+ '      var dx=ev.clientX-startX;var dy=ev.clientY-startY;'
+ '      if(Math.abs(dx)>3||Math.abs(dy)>3)dragging=true;'
+ '      if(dragging){'
+ '        var newLeft=origLeft+dx;'
+ '        var newBottom=origBottom-dy;'
+ '        newLeft=Math.max(0,Math.min(window.innerWidth-60,newLeft));'
+ '        newBottom=Math.max(0,Math.min(window.innerHeight-60,newBottom));'
+ '        dragEl.style.left=newLeft+"px";'
+ '        dragEl.style.bottom=newBottom+"px";'
+ '        dragEl.style.top="auto";'
+ '      }'
+ '    };'
+ '    document.onmouseup=function(){'
+ '      document.onmousemove=null;document.onmouseup=null;'
+ '      if(dragging){'
+ '        localStorage.setItem("music-ball-pos",JSON.stringify({'
+ '          left:parseInt(dragEl.style.left),'
+ '          bottom:parseInt(dragEl.style.bottom)'
+ '        }));'
+ '        setTimeout(function(){dragging=false;},10);'
+ '      }'
+ '    };'
+ '  };'
+
+ '  // 点击面板外部关闭'
+ '  document.addEventListener("click",function(e){'
+ '    if(!dragging&&panelOpen&&!dragEl.contains(e.target)){'
+ '      panelOpen=false;document.getElementById("music-panel").classList.remove("show");'
+ '    }'
+ '  });'
+
+ '  init();'
+ '})();'
+ '<\/script>');
